version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: link-kicker-postgres
    environment:
      POSTGRES_DB: link_kicker
      POSTGRES_USER: link_kicker
      POSTGRES_PASSWORD: link_kicker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: link-kicker-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: