-- upgrade --
CREATE TABLE IF NOT EXISTS "statisticsrecord" (
    "id" SERIAL NOT NULL PRIMARY KEY,
    "dt_create" TIMESTAMPTZ NOT NULL  DEFAULT CURRENT_TIMESTAMP,
    "intent" VARCHAR(10) NOT NULL
);
COMMENT ON COLUMN "statisticsrecord"."intent" IS 'RANDOM: random\nADD: add\nDELETE: delete\nREAD: read\nSTATISTICS: statistics\nFEEDBACK: feedback\nHOUR: hour\nLINKS: links';
CREATE TABLE IF NOT EXISTS "user" (
    "id" SERIAL NOT NULL PRIMARY KEY,
    "dt_create" TIMESTAMPTZ NOT NULL  DEFAULT CURRENT_TIMESTAMP,
    "dt_update" TIMESTAMPTZ NOT NULL  DEFAULT CURRENT_TIMESTAMP,
    "tg_id" INT NOT NULL UNIQUE,
    "hour" SMALLINT
);
CREATE TABLE IF NOT EXISTS "link" (
    "id" SERIAL NOT NULL PRIMARY KEY,
    "dt_create" TIMESTAMPTZ NOT NULL  DEFAULT CURRENT_TIMESTAMP,
    "dt_update" TIMESTAMPTZ NOT NULL  DEFAULT CURRENT_TIMESTAMP,
    "url" VARCHAR(1024) NOT NULL,
    "was_read" BOOL NOT NULL  DEFAULT False,
    "owner_id" INT NOT NULL REFERENCES "user" ("id") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "aerich" (
    "id" SERIAL NOT NULL PRIMARY KEY,
    "version" VARCHAR(255) NOT NULL,
    "app" VARCHAR(20) NOT NULL,
    "content" JSONB NOT NULL
);
